"""Adding new fields to user model

Revision ID: 453395fe75c1
Revises: ee961b567e75
Create Date: 2025-01-22 09:54:52.505334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453395fe75c1'
down_revision = 'ee961b567e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_prefered', sa.String(), nullable=True))
    op.add_column('user', sa.Column('categories_prefered', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('legal_info', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('contacts', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('payment_method', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'payment_method')
    op.drop_column('user', 'contacts')
    op.drop_column('user', 'legal_info')
    op.drop_column('user', 'categories_prefered')
    op.drop_column('user', 'language_prefered')
    # ### end Alembic commands ###
